

//MARK: - DATE FORMAT
let EVENT_DATETIME_FORMAT = "YYYY-MM-dd HH:mm:ss"
let EVENT_DATE_FORMAT = "YYYY-MM-dd"
let EVENT_DAY_FORMAT = "dd"
let EVENT_TIME_FORMAT = "HH:MM"
let EVENT_MONTH_FORMAT = "MMM"
